[@@@comment "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
module Dataset =
  struct
    type t = Ojs.t
    let rec (t_of_js : Ojs.t -> t) = fun x2 -> x2
    and (t_to_js : t -> Ojs.t) = fun x1 -> x1
    let (t_to_js : t -> Ojs.t) = t_to_js
    let (t_of_js : Ojs.t -> t) = t_of_js
  end
type t = Ojs.t
let rec (t_of_js : Ojs.t -> t) = fun x6 -> x6
and (t_to_js : t -> Ojs.t) = fun x5 -> x5
let (t_to_js : t -> Ojs.t) = t_to_js
let (t_of_js : Ojs.t -> t) = t_of_js
let (datasets : t -> Dataset.t Chartjs_array.Any.t) =
  fun x9 ->
    Chartjs_array.Any.t_of_js Dataset.t_of_js
      (Ojs.get (t_to_js x9) "datasets")
let (set_datasets : t -> Dataset.t list -> unit) =
  fun x11 ->
    fun x12 ->
      Ojs.set (t_to_js x11) "datasets" (Ojs.list_to_js Dataset.t_to_js x12)
let (labels : t -> Chartjs_array.String.t) =
  fun x14 -> Chartjs_array.String.t_of_js (Ojs.get (t_to_js x14) "labels")
let (set_labels : t -> string list -> unit) =
  fun x15 ->
    fun x16 ->
      Ojs.set (t_to_js x15) "labels" (Ojs.list_to_js Ojs.string_to_js x16)
let (x_labels : t -> Chartjs_array.String.t) =
  fun x18 -> Chartjs_array.String.t_of_js (Ojs.get (t_to_js x18) "xLabels")
let (set_x_labels : t -> string list -> unit) =
  fun x19 ->
    fun x20 ->
      Ojs.set (t_to_js x19) "xLabels" (Ojs.list_to_js Ojs.string_to_js x20)
let (y_labels : t -> Chartjs_array.String.t) =
  fun x22 -> Chartjs_array.String.t_of_js (Ojs.get (t_to_js x22) "yLabels")
let (set_y_labels : t -> string list -> unit) =
  fun x23 ->
    fun x24 ->
      Ojs.set (t_to_js x23) "yLabels" (Ojs.list_to_js Ojs.string_to_js x24)
let (make :
  ?datasets:Dataset.t list ->
    ?labels:string list ->
      ?x_labels:string list -> ?y_labels:string list -> unit -> t)
  =
  fun ?datasets:x26 ->
    fun ?labels:x27 ->
      fun ?x_labels:x28 ->
        fun ?y_labels:x29 ->
          fun () ->
            let x30 = Ojs.empty_obj () in
            (match x26 with
             | Some x37 ->
                 Ojs.set x30 "datasets" (Ojs.list_to_js Dataset.t_to_js x37)
             | None -> ());
            (match x27 with
             | Some x35 ->
                 Ojs.set x30 "labels" (Ojs.list_to_js Ojs.string_to_js x35)
             | None -> ());
            (match x28 with
             | Some x33 ->
                 Ojs.set x30 "xLabels" (Ojs.list_to_js Ojs.string_to_js x33)
             | None -> ());
            (match x29 with
             | Some x31 ->
                 Ojs.set x30 "yLabels" (Ojs.list_to_js Ojs.string_to_js x31)
             | None -> ());
            t_of_js x30
